sana_builder/webapp/templates/common/nav.html
sana_builder/webapp/templates/webapp/login.html
sana_builder/webapp/templates/webapp/signup.html

Added login/signup form

---

scripts/export_flatpages.bash
src/README.md

A good refresher when coming back to this project.

Added README in src with commonly used commands

---

.travis.yml
fabfile.py
requirements.txt
setup.cfg
src/editor/models.py
src/editor/tests/test_example.py
src/editor/tests/test_model_procedure.py
src/editor/views.py
src/homepage/admin.py
src/homepage/context_processors.py
src/homepage/models.py
src/homepage/signals/user_post_save.py
src/homepage/tests/test_user.py
src/homepage/views.py
src/manage.py
src/sanaprotocolbuilder/settings.py
src/sanaprotocolbuilder/urls.py
src/sanaprotocolbuilder/wsgi.py

Enforces that the code follows the PEP-8 style guide for python and some linting.

Add flake8 as a python linter and styleguide

---

setup.cfg
src-backend/api/migrations/0003_auto_20150523_1952.py
src-backend/api/models.py
src-backend/api/tests/test_model_procedure.py

This includes procedures, pages, and elements

Add initial models for v1 demo

---

src-backend/api/serializer.py
src-backend/api/urls.py
src-backend/api/views.py

Add endpoint for procedures

---

src-backend/api/migrations/0004_auto_20150524_0107.py
src-backend/api/models.py
src-backend/api/serializer.py

Returns more information now. Serializer is also more lightweight.

Fix procedure endpoint

---

requirements.txt
src-backend/sanaprotocolbuilder/settings.py

Temporary until we get them living properly

Add cross-origin request handling for ember

---

requirements.txt
src-backend/api/serializer.py
src-backend/sanaprotocolbuilder/settings.py

Add new python egg that lets Django and ember not hate each other.
Also added pages to the procedure objects

Make json play nice with Ember

---

src-backend/sanaprotocolbuilder/settings.py

Now you can log to the console or file with:
```
import logging
logger = logging.getLogger('debugger')
logger.info('Hello World')
```
You can customize the logger in the settings file.

Add logging support

---

requirements.txt
src-backend/api/views.py
src-backend/sanaprotocolbuilder/settings.py

Return objects as camel-case

---

fabfile.py
src-backend/registration/forms.py
src-backend/registration/models.py
src-backend/registration/signals/user_post_save.py
src-backend/registration/tests/test_user.py
src-backend/registration/urls.py
src-backend/registration/views.py
src-backend/sanaprotocolbuilder/settings.py
src-backend/sanaprotocolbuilder/urls.py

Example usage (with HTTPie):
```
http -v --form POST localhost:8000/auth/signup \
username=test password1=test password2=test email=test0@test.com accept_tos=True
```

Add user registration endpoint

---

README.md
docs/INSTALL.md

- Changed README to general info about the project
- Moved installation instructions to docs/INSTALL.md
TODO: Need to clarify `docs/INSTALL.md` on what computer to run the commands on. We may just want to add a single bash script (with user defined variables at the top) to run all the commands. The important thing is to minimize the amount of commands we need to run to provision a brand new Ubuntu server.

Created docs folder

---

scripts/cloc-definitions.txt
scripts/cloc-ignore.txt
scripts/cloc.sh

This is for our final presentation when we have to give an accurate report on our progress.
```
$ ./cloc.sh 
95 text files.
91 unique files.                              
39 files ignored.
http://cloc.sourceforge.net v 1.60  T=0.47 s (148.5 files/s, 6039.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
LESS                             7            184            203            795
Javascript                      38            119             72            524
Python                          17            118             68            451
Markdown                         3             58 …
```

Added cloc script

---

src-frontend/app/adapters/application.js
src-frontend/app/app.js
src-frontend/app/components/modal-dialog.js
src-frontend/app/controllers/add-element-modal.js
src-frontend/app/controllers/edit-page-modal.js
src-frontend/app/controllers/login.js
src-frontend/app/controllers/procedure.js
src-frontend/app/models/element.js
src-frontend/app/models/page.js
src-frontend/app/models/procedure.js
src-frontend/app/router.js
src-frontend/app/routes/application.js
src-frontend/app/routes/procedure.js
src-frontend/app/routes/procedures/index.js
src-frontend/app/serializers/page.js

Please double-check that I didn't miss anything! :+1:

Change JavaScript files to 4 spaces

---

.flowconfig
fabfile.py

We aren't using it and we have some license issues.

Delete the flow linter

---

src-frontend/app/controllers/login.js
src-frontend/app/controllers/signup.js
src-frontend/app/router.js
src-frontend/app/routes/signup.js
src-frontend/app/templates/login.hbs
src-frontend/app/templates/signup.hbs
src-frontend/tests/unit/controllers/signup-test.js
src-frontend/tests/unit/routes/signup-test.js

Added signup page, at /signup

---

src-frontend/app/components/procedure-card.js
src-frontend/app/controllers/procedures/index.js
src-frontend/app/serializers/procedure.js
src-frontend/app/styles/base.less
src-frontend/app/templates/components/procedure-card.hbs
src-frontend/app/templates/procedures/index.hbs
src-frontend/tests/unit/components/procedure-card-test.js
src-frontend/tests/unit/controllers/procedures/index-test.js
src-frontend/tests/unit/serializers/procedure-test.js

Add procedure listing, plus a button for creating procedures

---

src-frontend/config/environment.js

Disabled CORS for development on Ember server

---

src-backend/sanaprotocolbuilder/middleware.py
src-backend/sanaprotocolbuilder/settings.py

This should help with debugging errors when we're making AJAX requests to the server

Add middleware to print 500 errors to console

---

README.md

Seems like we have a few out of date modules. Can someone upgrade them in a separate PR?

Add requirements checker to README

---

src-backend/api/signals/page_pre_save.py
src-backend/api/tests/test_model_page.py
src-backend/api/urls.py

Update indices of Pages on backend instead of batch puts on the frontend

---

src-backend/api/generator.py
src-backend/api/tests/test_generator.py
src-backend/api/views.py
src-frontend/app/controllers/procedure.js
src-frontend/app/templates/procedure.hbs
src-frontend/config/environment.js

Javascript part is a tad hacky, but that is the recommended way of doing it.
Still needs styling work.
Depends on #120

Generator API and file saving

---

mockups/choices.html
mockups/css/choices.less

CSS mockups for choices form

---

src-frontend/app/components/navigation-bar.js
src-frontend/app/templates/application.hbs
src-frontend/app/templates/components/navigation-bar.hbs
src-frontend/app/templates/index.hbs
src-frontend/app/templates/procedure.hbs
src-frontend/app/templates/procedures/index.hbs
src-frontend/bower.json
src-frontend/tests/unit/components/navigation-bar-test.js

Add a navigation bar

---

src-frontend/app/authenticators/token.js
src-frontend/app/components/navigation-bar.js
src-frontend/app/routes/procedure.js
src-frontend/app/routes/procedures.js
src-frontend/app/styles/app.less
src-frontend/app/templates/components/navigation-bar.hbs
src-frontend/config/environment.js

Plus a couple of usability improvements :dizzy:
Closes #151

Add logout support to the frontend

---

src-backend/api/generator.py
src-backend/api/tests/test_generator.py

Increase generator validation strictness and associated tests

---

requirements.txt
src-backend/sanaprotocolbuilder/settings.py

It has some really useful commands such as `show_urls` which shows all routes

Added django extensions to project

---

src-backend/api/field.py
src-backend/api/generator.py
src-backend/api/serializer.py
src-backend/api/tests/test_field_choices.py
src-backend/api/tests/test_generator.py

Fixes all the issues with storing choices in the database and retrieving
them

Add a custom field to serialize choices properly

---

requirements.txt
src-backend/api/migrations/0005_auto_20150703_2228.py
src-backend/api/models.py
src-backend/api/tests/test_generator.py
src-backend/api/tests/utils/factories.py

Factory boy auto-generates things and makes tests less boilerplatey.
Closes #114

Add factory boy to make tests look less gross

---

src-backend/api/serializer.py
src-frontend/app/controllers/edit-page-modal.js
src-frontend/app/controllers/procedure.js
src-frontend/app/styles/base.less
src-frontend/app/templates/components/element-cell.hbs
src-frontend/app/templates/edit-page-modal.hbs

This change does a few things.
1) On Page creation, we now create an element for the page
2) Removes the ability to add multiple elements to a page on the front-end
3) Makes choices a non-required field (to make things behave)
4) CSS changes

Make it so each page only has a single element.

---

requirements.txt

I'm going to assume nobody needs to review this...

Upgrade Django 1.8.2 to 1.8.3

---

fabfile.py

Just makes it easier to run from the root folder

Add fab command to start the python server.

---

src-frontend/app/components/procedure-card.js
src-frontend/app/styles/base.less
src-frontend/app/templates/components/procedure-card.hbs

This will allow us to delete existing procedures.
Closes #177

Add a button to the procedure cards to delete them.

---

src-frontend/app/routes/index.js

Transition to procedures if logged in

---

src-frontend/app/controllers/procedure.js

This is when we want to create a new page in between two pages.
Before it wasn't updating the display indices of the other pages.
Resolves #182

Fixed addition of pages at specific indexes

---

.travis.yml
fabfile.py
scripts/install-frontend.sh
src-frontend/.watchmanconfig
src-frontend/Brocfile.js
src-frontend/app/app.js
src-frontend/app/templates/components/page-list.hbs
src-frontend/app/templates/edit-page-modal.hbs
src-frontend/app/templates/procedures/index.hbs
src-frontend/bower.json
src-frontend/package.json
src-frontend/tests/unit/components/modal-dialog-test.js
src-frontend/tests/unit/components/navigation-bar-test.js
src-frontend/tests/unit/components/procedure-card-test.js
src-frontend/tests/unit/models/element-test.js
src-frontend/tests/unit/models/page-test.js
src-frontend/tests/unit/models/procedure-test.js
src-frontend/tests/unit/serializers/page-test.js
src-frontend/tests/unit/serializers/procedure-test.js

:information_source:  Resolves #166

Get Ember tests to run; add them to Fabric/Travis

---

src-frontend/app/authenticators/token.js

Fix infinite 403 errors(!!!)

---

src-frontend/app/styles/base.less
src-frontend/app/templates/components/page-list.hbs

Switched + with "Add Page"

---

src-frontend/package.json

Added PhantomJS to npm requirements

---

.travis.yml
fabfile.py
scripts/install-frontend.sh
src-backbone/app/index.html
src-backbone/app/js/main.coffee
src-backbone/app/js/sana_app.js
src-backbone/app/js/utils/setup.js
src-backbone/bower.json
src-backbone/package.json
src-backbone/tests/smoke_test.js
src-backbone/tests/utils/create_suite.js

The tests are headless so they need to load JS libs via require (loaded
from npm repository). As a result, we are no longer using libraries
loaded from bower. Those loaded from bower cannot be (easily) tested.
I also updated our package.json to remove some warnings.
Closes #213

Setup Backbone testing with mocha, chai, sinon

---

src-backbone/app/js/behaviors/auth_form_behavior.js
src-backbone/app/js/main.coffee
src-backbone/app/js/models/session.js
src-backbone/app/js/routers/auth/auth_controller.js
src-backbone/app/js/routers/auth/auth_router.js
src-backbone/app/js/routers/procedures/procedures_controller.js
src-backbone/app/js/routers/procedures/procedures_router.js
src-backbone/app/js/sana_app.js
src-backbone/app/js/utils/config.js
src-backbone/app/js/utils/helpers.js
src-backbone/app/js/utils/logger.js
src-backbone/app/js/utils/setup.js
src-backbone/app/js/utils/storage.js
src-backbone/app/js/views/auth/login_view.js
src-backbone/package.json
src-backbone/tests/auth/auth_controller_test.js
src-backbone/tests/auth/session_model_test.js
src-backbone/tests/smoke_test.js
src-backbone/tests/utils/create_suite.js

Also refactored exisiting code with dependency injection so that they're
easier to test.
Closes #214

Wrote tests for authentication module

---

src-backbone/app/js/routers/info/info_controller.js
src-backbone/app/js/routers/info/info_router.js
src-backbone/app/js/sana_app.js
src-backbone/app/js/templates/auth/signup.hbs
src-backbone/app/js/templates/info/info.hbs
src-backbone/app/js/templates/info/privacy_policy.hbs
src-backbone/app/js/templates/info/terms_of_service.hbs
src-backbone/app/js/views/info/info_layout.js

Terms of Service and Privacy Policy page

---

scripts/cloc-ignore.txt
scripts/cloc.sh

Slowly shrinking our code base
```
$ ./cloc.sh 
86 text files.
86 unique files.                              
29431 files ignored.
http://cloc.sourceforge.net v 1.60  T=1.31 s (55.1 files/s, 2780.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          37            421            115           1498
Javascript                      27            300            176           1016
LESS                             4              5              0             44
HTML                             1              4              0             18
Markdown …
```

Update cloc script

---

src-backbone/gulpfile.js

Run JS Lint on tests too

---

src-backbone/app/js/behaviors/authFormBehavior.js
src-backbone/app/js/views/auth/loginView.js
src-backbone/app/js/views/auth/signupView.js
src-backbone/tests/auth/authFormBehavior_test.js
src-backbone/tests/auth/loginView_test.js
src-backbone/tests/auth/signupView_test.js

This contains tests for
- `loginView`
- `signupView`
- `AuthFormBehavior`

Finished auth module tests

---

src-backbone/app/js/models/procedure.js
src-backbone/app/js/templates/builder/pageElements/elementItemView.hbs
src-backbone/app/js/utils/helpers.js
src-backbone/app/js/views/builder/builderHeaderView.js
src-backbone/app/js/views/builder/pageElements/elementItemView.js
src-backbone/app/js/views/procedures/proceduresItemView.js

Implement procedure download

---

src-django/api/migrations/0007_concept.py
src-django/api/models.py
src-django/api/tests/test_model_concept.py
src-django/api/tests/utils/factories.py

Add model and tests for concept

---

src-django/api/serializer.py
src-django/api/startup.py
src-django/api/tests/test_concepts.py
src-django/api/urls.py
src-django/api/views.py

Add API support for concepts

---

src-django/api/migrations/0008_conditionnode_showif.py
src-django/api/models.py
src-django/api/tests/test_model_condition_node.py
src-django/api/tests/test_model_showif.py
src-django/api/tests/utils/factories.py

I'm not sure the best way to get the children # validation working because django doesn't allow for OneToMany as a specifier. Otherwise, this should be the basis for conditonals

Create models for conditional logic

---

src-django/api/generator.py
src-django/api/migrations/0010_remove_element_concept.py
src-django/api/migrations/0011_element_concept.py
src-django/api/models.py
src-django/api/tests/test_generator.py
src-django/api/tests/test_model_element.py
src-django/api/tests/utils/factories.py

Resolves #283.
Used to be a `TextField`.

Make `concept` a foreign key on `Element`

---

src-backbone/app/js/models/element.js
src-backbone/app/js/templates/builder/pageElements/types/pluginEntryView.hbs
src-backbone/app/js/templates/builder/pageElements/types/pluginView.hbs
src-backbone/app/js/utils/configTemplate.js
src-backbone/app/js/views/builder/pageElements/elementItemView.js
src-django/api/generator.py
src-django/api/migrations/0012_auto_20160216_2324.py
src-django/api/models.py
src-django/api/serializer.py
src-django/api/tests/test_generator.py
src-django/api/tests/test_model_element.py
src-django/api/tests/utils/factories.py

Shouldn't break the front-end...
Closes #262

Update elements to the latest version of the protocol spec

---

src-backbone/app/js/sanaApp.js

This should fix the timeouts some tests are getting due to calling
_setupSession() with fetch() inside.

Moved session fetch to init() method

---

src-backbone/app/js/controllers/authController.js
src-backbone/app/js/models/session.js
src-backbone/app/js/routers/authRouter.js
src-backbone/app/js/templates/auth/settingsView.hbs
src-backbone/app/js/views/auth/settingsView.js
src-backbone/app/locales/en/translation.json
src-backbone/tests/auth/authController_test.js
src-django/api/serializer.py
src-django/api/startup.py
src-django/api/tests/test_users.py
src-django/api/urls.py
src-django/api/views.py

Added user account endpoint to update info

---

src-backbone/app/js/sanaApp.js
src-backbone/app/js/utils/helpers.js
src-backbone/app/js/views/builder/builderHeaderView.js
src-backbone/app/js/views/builder/pageElements/choices/choicesItemView.js
src-backbone/app/js/views/builder/pageElements/elementItemView.js

This should properly throttle updating while typing in any field.

Use debounce instead of delaySave for proper request throttling

---

src-backbone/app/js/views/builder/builderHeaderView.js
src-backbone/app/js/views/builder/pageElements/choices/choicesItemView.js
src-backbone/app/js/views/builder/pageElements/elementItemView.js

Ooops, the original method was the only way to do it.

Fixed debounce null reference error

---

src-backbone/app/js/models/element.js
src-backbone/app/js/templates/builder/pageElements/types/pluginEntryView.hbs
src-backbone/app/js/templates/builder/pageElements/types/pluginView.hbs
src-backbone/app/js/utils/configTemplate.js
src-backbone/app/js/views/builder/pageElements/elementItemView.js
src-backbone/app/js/views/builder/pageElements/types/entryView.js
src-backbone/app/js/views/builder/pageElements/types/pluginEntryView.js
src-backbone/app/js/views/builder/pageElements/types/pluginView.js
src-backbone/app/locales/en/translation.json

Closes #307 
One small weirdity with mime-type still. May require renaming the field on the server to something else to make it behave.

Correctly capture events from child views in elements

---

src-backbone/app/js/templates/builder/pageElements/elementItemView.hbs
src-backbone/app/js/views/builder/pageElements/elementItemView.js
src-backbone/app/locales/en/translation.json

Paving the way for concepts ui

Remove the concept field inside elements from the ui

---

src-django/authentication/tests/test_login.py
src-django/authentication/views.py

Includes if user is super user to use to determine if they can upload
a concept dictionary CSV.
Resolves #337

Send back user info on login

---

src-django/api/generator.py
src-django/api/tests/test_generator.py

Create generator support for conditional logic

---

src-backbone/app/css/main.less
src-backbone/app/css/modules/builderPageDetails.less
src-backbone/app/js/models/element.js
src-backbone/app/js/templates/builder/pageElements/elementItemView.hbs
src-backbone/app/js/templates/builder/pageElements/types/choicesView.hbs
src-backbone/app/js/templates/builder/pageElements/types/dateView.hbs
src-backbone/app/js/templates/builder/pageElements/types/entryView.hbs
src-backbone/app/js/templates/builder/pageElements/types/pluginEntryView.hbs
src-backbone/app/js/templates/builder/pageElements/types/pluginView.hbs
src-backbone/app/js/utils/setup.js
src-backbone/app/js/views/builder/pageElements/elementItemView.js
src-backbone/app/js/views/builder/pageElements/types/dateView.js
src-backbone/app/js/views/builder/pageElements/types/entryView.js
src-backbone/app/js/views/builder/pageElements/types/pluginEntryView.js
src-backbone/app/js/views/builder/pageElements/types/pluginView.js
src-backbone/app/js/views/builder/pageElements/types/radioView.js
src-backbone/app/locales/en/translation.json
src-backbone/gulpfile.js
src-backbone/package.json

- Implemented Date editor (Closes #265)
- Cleaned up Plugin, PluginEntry, Entry editors (Closes #267)

Cleaned up Elements editor

---

src-backbone/app/css/modules/info.less
src-backbone/app/js/controllers/infoController.js
src-backbone/app/js/routers/infoRouter.js
src-backbone/app/js/templates/info/creditsView.hbs
src-backbone/app/js/templates/procedures/proceduresLayoutView.hbs
src-backbone/app/js/utils/configTemplate.js
src-backbone/app/js/utils/helpers.js

Added Credits page

---

src-django/api/tests/test_concepts.py
src-django/api/views.py

Add the ability to search concepts

---

src-django/api/serializer.py

Properly check that the answer is in choices for select elements

---

.travis.yml
fabfile.py
src-django/api/__init__.py
src-django/api/apps.py
src-django/api/startup.py
src-django/api/urls.py
src-django/authentication/__init__.py
src-django/authentication/apps.py
src-django/mailer/__init__.py
src-django/mailer/apps.py
src-django/requirements.txt
src-django/sanaprotocolbuilder/settings.py

This change allows the transition to 1.9 if we want to upgrade now or later.

Upgrade requirements

---

src-django/api/tests/test_users.py
src-django/api/views.py
src-django/authentication/views.py

Also return `id` from login details.

Return user info on account change

---

src-backbone/app/css/modules/builderPageDetails.less
src-backbone/app/js/behaviors/choiceBasedElementBehavior.js
src-backbone/app/js/collections/choices.js
src-backbone/app/js/models/choice.js
src-backbone/app/js/models/element.js
src-backbone/app/js/templates/builder/pageElements/choices/choicesItemView.hbs
src-backbone/app/js/utils/setup.js
src-backbone/app/js/views/builder/pageElements/choices/choicesCollectionView.js
src-backbone/app/js/views/builder/pageElements/choices/choicesItemView.js
src-django/api/field.py
src-django/api/generator.py
src-django/api/serializer.py
src-django/api/tests/test_field_choices.py
src-django/api/tests/test_generator.py
src-django/api/tests/utils/factories.py

Allows multi-select answers to work properly. Needs updates on the front-end still.
Closes #336

Fixes for Choice editor

---

src-backbone/app/js/controllers/conceptsController.js
src-backbone/app/js/models/session.js
src-backbone/app/js/models/user.js
src-backbone/app/js/routers/conceptsRouter.js
src-backbone/app/js/sanaApp.js
src-backbone/app/js/templates/common/loggedInRightNavbarView.hbs
src-backbone/app/js/templates/concepts/conceptUploaderView.hbs
src-backbone/app/js/templates/concepts/conceptsLayoutView.hbs
src-backbone/app/js/views/common/loggedInRightNavbarView.js
src-backbone/app/js/views/concepts/conceptsLayoutView.js
src-backbone/app/js/views/concepts/conceptsUploaderView.js
src-backbone/app/locales/en/translation.json
src-backbone/test/unit/auth/authController_test.js
src-backbone/test/unit/auth/loginView_test.js
src-backbone/test/unit/auth/signupView_test.js
src-backbone/test/unit/sanaApp_test.js

Only displays on right navbar when user is a superuser

Frontend view for concept uploader

---

src-backbone/app/js/behaviors/rightNavbarBehavior.js
src-backbone/app/js/utils/configTemplate.js

Correctly hide the language selector

---

src-backbone/app/js/controllers/conceptsController.js
src-backbone/app/js/models/session.js
src-backbone/app/js/models/user.js
src-backbone/app/js/sanaApp.js
src-backbone/app/js/views/auth/settingsView.js
src-backbone/app/js/views/common/loggedInRightNavbarView.js
src-backbone/test/unit/auth/sessionModel_test.js

Moved away most of the user details logic to the User model.
Sessions holds a global user object that gets updated on login.

[Maybe WIP] Moved user related functions to user model

---

src-django/api/generator.py
src-django/api/tests/test_generator.py

Invalidates/Closes #293.
It escapes strings.

Add test to prove xml escapes strings

---

src-backbone/gulpfile.js
src-backbone/package.json

This helps when the auto-reload misbehaves. We should have this anyway....

Add gulp clean command

---

src-backbone/app/js/templates/builder/pageDetails/pageElements/elementItemView.hbs
src-backbone/app/js/utils/setup.js

Properly set the value of the required checkbox

---

src-backbone/app/js/models/page.js

Newer version of jshint didn't like this...

Fix jshint warning about creating a function in a loop

---

src-backbone/app/js/models/conditionals/conditionalNode.js
src-backbone/app/js/models/page.js

There's no issue open for these minor bug fixes

Fixes for condition node

---

src-backbone/app/js/templates/builder/pageDetails/pageConditions/conditionalNodeView.hbs

Fixed mismatched strings for conditional dropdown

---

src-backbone/app/js/templates/builder/pageDetails/pageConditions/conditionalNodeView.hbs
src-backbone/app/locales/en/translation.json

Related to #394. Shortens the hint in the dropdown.

Shorten Element to check to just Element

---

src-backbone/app/js/models/page.js
src-backbone/app/js/models/procedure.js
src-backbone/app/js/views/builder/pageList/pageListItemView.js

Fixes the issue where updating a question on an element doesn't actually update the left-nav.

Trigger render on left-nav when an element is updated

---

src-backbone/app/js/controllers/authController.js
src-backbone/app/js/models/session.js
src-backbone/app/js/routers/authRouter.js
src-backbone/app/js/views/auth/confirmEmailView.js
src-backbone/app/locales/en/translation.json
src-backbone/test/unit/auth/authController_test.js
src-backbone/test/unit/auth/sessionModel_test.js
src-django/authentication/views.py

Now when a user signs up, it redirects them to the logged in page. For email confirmation, added a view that hits the backend to confirm user's email. It then redirects to the appropriate page depending on session.
Resolves #366 
Squashes #373

Login Issues

---

src-backbone/app/js/templates/builder/pageDetails/pageConditions/conditionalNodeView.hbs

Change expand/contract icons for conditional logic

---

src-backbone/app/css/modules/builderPageList.less

Truncate long question text with ellipsis

---

src-backbone/package.json

Cap i18next version

---

src-backbone/app/js/templates/auth/settingsView.hbs
src-backbone/app/js/views/auth/settingsView.js

Added user model to account settings

---

src-backbone/app/js/templates/builder/builderHeaderView.hbs
src-backbone/app/locales/en/translation.json

Change the "Download" button to "Download XML" in the builder

---

src-backbone/app/js/views/builder/builderHeaderView.js

Re-render the header once, to populate the title and author

---

src-backbone/app/js/templates/builder/pageDetails/pageConditions/conditionalNodeView.hbs
src-backbone/app/locales/en/translation.json

Make "When Any/When All" dropdown just "any/all"

---

src-backbone/app/js/collections/concepts.js
src-backbone/app/js/templates/builder/pageDetails/pageElements/concepts/conceptListItemView.hbs
src-django/api/views.py

Use display_name instead of name for concept select and search

---

src-backbone/app/css/modules/builderPageDetails.less
src-backbone/app/js/models/conditionals/conditionalNode.js
src-backbone/app/js/templates/builder/pageDetails/pageConditions/conditionalNodeView.hbs
src-backbone/app/js/views/builder/pageDetails/pageConditions/conditionalNodeView.js

- Changed add behaviour so that you add to a parent node. Closes #437
- Removed add button from criteria nodes which gives value more space. Closes #395 for now.
- Move the expand/contract button to the left side of the condition node ui area. Closes #447

Fix a bunch of condition node UX problems

---

src-backbone/app/css/modules/builderPageList.less

Can't seem to make them size to fit, but this will at least make them fit most conditionals. ¯\\_(ツ)_/¯

Make popovers bigger

---

src-backbone/app/js/controllers/infoController.js
src-backbone/app/js/routers/infoRouter.js
src-backbone/app/js/templates/auth/signupView.hbs
src-backbone/app/js/templates/info/privacyPolicyView.hbs
src-backbone/app/js/templates/info/termsOfServiceView.hbs
src-backbone/app/js/templates/procedures/proceduresLayoutView.hbs
src-django/authentication/forms.py
src-django/authentication/tests/test_signup.py

For now removing them.
Temporarily Closes #383 
Temporarily Closes #382

Remove ToS and Privacy Policy for now

---

src-backbone/app/js/collections/concepts.js

Minor logging spelling fix

---

src-backbone/app/js/behaviors/rightNavbarBehavior.js

Remove language selector require
