chef/Gemfile.lock

As per https://www.chef.io/blog/2014/12/02/postmortem-ohai-mixlib-shellout-gem-release-issues/

Update mixlib gem to fix bundler errors

---

src-backend/sanaprotocolbuilder/settings.py

Since Django is not serving any pages, we don't need `TEMPLATE_CONTEXT_PROCESSORS `.

Cleaned up settings file

---

scripts/cloc.sh

```
$ ./cloc.sh 
98 text files.
94 unique files.                              
36350 files ignored.
http://cloc.sourceforge.net v 1.60  T=2.59 s (27.8 files/s, 1124.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
LESS                             7            184            203            799
Javascript                      39            126             72            564
Python                          18            123             69            461
Markdown                         3             58             13            111
HTML                             3             15 …
```

Modified CLOC script to ignore temp directories

---

docs/DEPLOY.md
docs/INSTALL.md
docs/SETUP_DEVELOPMENT.md

Currently doing bundle install inside chef requires 1.9.3 Ruby.
Also, bundler is a gem, so we need to get gem and then do a `gem install bundler`

Modified install docs to account for bundler

---

src-frontend/app/controllers/edit-page-modal.js
src-frontend/app/controllers/procedure.js
src-frontend/app/helpers/plus-one.js
src-frontend/app/templates/components/page-list.hbs
src-frontend/bower.json
src-frontend/tests/unit/helpers/plus-one-test.js

Now that display indices are updated in the backend, we can get rid of the old client code.
Note: reordering is still broken. this is just for adding new pages

Clean up page indexing

---

src-backend/sanaprotocolbuilder/settings.py

When the Rest framework tries to return an error page, it tries to load static files via the staticfiles module. Since we removed it back when we decoupled the frontend from the backend, the Rest framework can't properly serve up its error pages (e.g. 401 invalid token).
Fixes:

Fix staticfile errors

---

src-frontend/.jshintrc

Only check for unused variables; not unused function parameters

Fix JSHint errors

---

src-backend/api/serializer.py
src-backend/api/tests/test_procedures.py
src-backend/api/views.py
src-frontend/app/controllers/procedures/index.js

We no longer need to specify the owner when creating a procedure. It will be pulled out of the request and injected into the serializer.

Inject the owner automatically into created procedures

---

src-frontend/app/components/page-list.js
src-frontend/app/controllers/procedure.js

Deletion now calls `updateSortOrder` to update the display indices
New function within procedure that will generate a new page indices array.
Let me know if we should move that function somewhere else, or if we should add extra things into the `pageModel` array it returns, or a name change :dash:

Fixed re-indexing `display_index` after deletion

---

src-backend/api/migrations/0006_auto_20150714_2302.py
src-backend/api/models.py
src-backend/api/tests/test_model_page.py
src-backend/api/tests/test_model_procedure.py
src-frontend/app/controllers/procedures/index.js
src-frontend/app/helpers/date-string.js
src-frontend/app/models/procedure.js
src-frontend/app/templates/components/procedure-card.hbs
src-frontend/app/templates/procedures/index.hbs

Depends on #187 because of UI.
Does two things.
1. Fixes updating last_modified timestamps for models on the server so that child elements (pages, elements) cascade their updates to their parents.
2. Makes it so that procedures use their actual last_modified timestamp and are sorted in the correct order.

Update and handle last_modified timestamps correctly.

---

src-frontend/app/controllers/signup.js
src-frontend/app/styles/base.less
src-frontend/app/templates/application.hbs
src-frontend/package.json
src-frontend/tests/helpers/flash-message.js
src-frontend/tests/test-helper.js

I've used https://github.com/poteto/ember-cli-flash to implement the flash messages. So far we only have it in the sign up page, but @ConnorCimowsky can add them into the login flow (I'm not 100% sure how to work the auth flow so I'll leave that to Connor).
The CSS changes are because by default the flash message takes up pretty much 100% of the screen, which doesn't look very good.
Resolves #123 
Screenshot: 
TODO: Add form validations and add the errors into the flash messages (i.e. missing fields). Will do in another ticket

Added in flash messages

---

.travis.yml

This allows Travis to use the new container-based infrastructure:
http://docs.travis-ci.com/user/migrating-from-legacy/

Don't use sudo for Travis

---

scripts/dev_setup_linux.bash
scripts/dev_setup_osx.bash

Probably should wait until #193 is merged in, but this cleans up some things and makes setup scripts not use sudo.

Remove sudo's and cleanup start scripts

---

src-frontend/app/controllers/procedure.js
src-frontend/app/templates/components/modal-dialog.hbs

This change moves the logic for adding an element to a page automatically to the edit functionality of the page creation versus on creation. It also changes "cancel" to "close" to make it more explicit what it is doing.
Sorta resolves #178 in a different way.

Clean up some of the create page UX

---

src-backend/api/models.py
src-backend/api/tests/test_model_element.py
src-backend/api/tests/test_model_page.py
src-backend/api/tests/test_model_procedure.py

Gives some validation for the element models and cleans up the page/procedure model tests a lot.
Additionally, covers some missing cases from procedures and pages as well.
Also fixes a bug that was found in creating the element tests. The server was not validating the type of the element properly and that is now fixed.
Closes #101

Add element unit tests and refactor page and procedure unit tests

---

src-backbone/app/js/utils/logger.js

Use native console when trying to print non-strings.

Logger use native console when message is an object

---

src-backbone/app/js/views/procedures/procedures_item_view.js

If Marionette detects the the initial collection is not sorted properly,
it will re-render the CollectionView on page load.

Fixed FOUC when procedures are not sorted

---

src-django/api/serializer.py
src-django/api/tests/test_procedures.py
src-django/api/tests/utils/helpers.py
src-django/api/views.py

only_return_id flag for procedures, when set true, will result in a
response with only page ids for each procedure. If however it is set
to false, then instead of page ids, the full page object will be returned.
Resolves #256

Updated procedure API to include only_return_id

---

src-django/sanaprotocolbuilder/settings.py

I don't think we even read the info.log file that gets generated and it's quite annoying to see log files in my directories.
Closes #254

Removed generating Django log file for auth module

---

src-backbone/app/js/models/procedure.js

/procedures responds with an array of page objects instead of array of
page ids in #260

Fixed page loading in Procedure model

---

src-django/api/migrations/0009_auto_20160211_2019.py
src-django/api/models.py
src-django/api/serializer.py
src-django/api/startup.py
src-django/api/tests/test_conditionals.py
src-django/api/tests/test_model_condition_node.py
src-django/api/tests/test_model_show_if.py
src-django/api/tests/utils/factories.py
src-django/api/urls.py
src-django/api/views.py
src-django/requirements.txt

Still missing a lot of tests, but this should be the serialization and api for condition logic.
Example POST:
```
{
"page":1,
"conditions": [
{
"node_type": "NOT",
"children": [
{
"node_type": "AND",
"children": [
{
"criteria_element": 3,
"node_type": "CRITERIA",
"criteria_type": "EQUALS",
"value": "foo"
},
{
"criteria_element": 3,
"node_type": "CRITERIA",
"criteria_type": "EQUALS",
"value": "bar"
}
]
}
]
}
]
}
```

Implement condition logic serialization

---

src-django/requirements.txt
src-django/sanaprotocolbuilder/settings.py

This allows us to connect to redis using the internal django cache libraries. Redis is already running for Celery, this allows us to connect to it via django's internal caching system. We can use:
`from django.core.cache import cache` and then use redis library functions like `set` and `get`
And then, when we want to test functionality, we can use django's `@override_settings` or `@modify_settings`
```
@modify_settings(CACHES={
'default': 'django.core.cache.backends.locmem.LocMemCache',
})
```
Resolves  #316

Added a redis cache system for django

---

src-django/mailer/templater.py

This commit adds a template directory under `api` for storing our jinja templates. The templater module is just to load the template environment. Then, once you have the environment object returned by `get_environment` you can:
Load up your template by name: `template = env.get_template('template_name.html')`
And then you can render it: `template.render(your='variables', go='here')`
So, if we have a template like
```
Hello {{ name }},  I'm {{ sender }}.
```
we can render the template like this: `template.render(name='Geoff', sender='Lenny')`
and we'll get `Hello Geoff, I'm Lenny`
Resolves #317

Added jinja2 template loader module & template dir

---

src-backbone/app/js/templates/rootLayoutView.hbs
src-backbone/app/js/views/builder/pageDetails/pageElements/modalRegion.js
src-backbone/app/js/views/rootLayoutView.js

This is a part of my work on a concept picker, but @Ommy needs it now.
I will eventually make a `ModalLayoutView` to abstract the Bootstrap HTML mechanics, but I just wanted to get this out ASAP.
Here's the rundown:
1. Make a new template and view for the contents of the modal — the template must conform to the Bootstrap convention for modals (but the view does not need to be a `LayoutView` as shown below):
```html
<div class="modal-dialog">
<div class="modal-content">
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal"><span>&times;</span></button>
<h4 class="modal-title">{{ i18n "Modal Title" }}</h4>
</div>
<div class="modal-body">
...
</div>
</div>
</div>
```
```javascript
// app/js/views/.../someView.js
module.exports = Marionette.LayoutView.extend({ …
```

Add a Marionette region for displaying modals

---

src-backbone/app/js/models/procedure.js
src-backbone/app/js/templates/auth/signupView.hbs
src-backbone/app/js/views/procedures/proceduresNavbarView.js
src-backbone/app/locales/en/translation.json
src-django/authentication/forms.py
src-django/authentication/tests/test_signup.py

Change does two key things
1. Adds first name and last name to the signup form
2. Makes the author field on procedure default to owner's full name if it is blank or non-existent.
3. Fixes the "Hello username" field
4. Fixes translations
Closes #368, #365, #380, #381

Properly get and use the user's name

---

src-backbone/app/css/modules/auth.less
src-backbone/app/css/modules/procedures.less
src-backbone/app/js/templates/procedures/proceduresLayoutView.hbs

Reduce margins and padding on the auth and procedures page so they fit properly on smaller screens. More emphasis on the content, rather than headers.
Closes #372, #374

Cleanup Styling

---

src-django/api/models.py
src-django/api/tests/test_model_procedure.py

It defaults to this, but better for my piece of mind and it becomes mandatory to do this in Django 2.0

Explicitly make all foreign key deletes cascade

---

src-backbone/app/css/modules/builder.less
src-backbone/app/js/templates/builder/builderHeaderView.hbs
src-backbone/app/js/views/builder/builderHeaderView.js
src-backbone/app/locales/en/translation.json

Save button is right beside the download button, and it just calls the
direct saveToServer function since it isn't autosaving
Resolves #403

Added a save button on builder header

---

src-backbone/app/js/models/concept.js
src-backbone/app/js/models/element.js
src-backbone/app/js/models/page.js
src-backbone/app/js/models/procedure.js

For some reason, only in Safari, `parse` is called with an empty response and then subsequently called with the populated response. This caused errors to be thrown, so I added a check for an early return.
EDIT: Looks like this is more complicated, let's hold off for now.

Add a check for empty responses in parse functions

---

src-backbone/app/css/modules/builderPageDetails.less
src-backbone/app/js/templates/builder/pageDetails/pageElements/concepts/conceptCollectionEmptyView.hbs
src-backbone/app/js/templates/builder/pageDetails/pageElements/subroutines/subroutineCollectionEmptyView.hbs
src-backbone/app/js/views/builder/pageDetails/pageElements/concepts/conceptCollectionEmptyView.js
src-backbone/app/js/views/builder/pageDetails/pageElements/concepts/conceptCollectionView.js
src-backbone/app/js/views/builder/pageDetails/pageElements/subroutines/subroutineCollectionEmptyView.js
src-backbone/app/js/views/builder/pageDetails/pageElements/subroutines/subroutineCollectionView.js

Previously when a user had no Concepts or Subroutines available, an empty search bar was shown in the respective modal. This PR adds emptyViews for these elements that:
1. Indicate that there are no Concepts/Subroutines.
2. Provide a link to the Concept/Subroutine manager if the user has sufficient privileges.
Screenshots:
Concepts modal with items:
Empty concepts modal (user can access Concepts Manager):
Empty concepts modal (user cannot access Concepts Manager):
Likewise, for Subroutines:
Empty Subroutines modal (user can access Subroutines Manager):
Empty Subroutines modal (user cannot access Subroutines Manager):

Add empty views for Concept and Subroutine modals

---

src-backbone/app/js/views/builder/pageDetails/pageElements/elementsCompositeView.js

Add specific "Choose Concept" and "Choose Subroutine" headings for Concept and Subroutine modals:
Concepts:
Subroutines:

Add specific modal names for Concepts and Subroutines

---

src-backbone/test/unit/auth/authController_test.js
src-backbone/test/unit/auth/loginView_test.js
src-backbone/test/unit/auth/signupView_test.js
src-backbone/test/unit/sanaApp_test.js

Some JS tests were failing after subroutines were added because the subroutines router was not properly stubbed. This adds the appropriate stubbing, and I confirmed that all JS tests now pass with gulp test.

Add subroutines router stub to JS tests

---

src-django/api/generator.py
src-django/api/views.py

Procedures used to have a different permission model where they could be accessed by users that were not their owner. This is no longer the case, so users should not be able to generate a procedure they do not own.

Raise exception if user tries to generate an unowned procedure.

---

src-django/api/tests/test_generator.py

The implementation was previously changed without an update to the test.

Correct test for choice generation.

---

src-django/api/tests/fixtures/concepts_valid.csv

Some column names were invalid, so tests that used this fixture were failing.

Fix valid concepts fixture.

---

src-django/api/tests/test_generator.py

Fixes a mistake in https://github.com/SanaMobile/sana.protocol_builder/commit/731e0598088c427daa08d339a651f91f09af9269 that broke a test.

Fix test_element_has_version_attrib to actually read version.
